using ProjectManager.Contracts.Services;
using System.Collections.Generic;
using System.Net;
using System.Net.Mail;

namespace ProjectManager.Services
{
    public class MailService : IMailService
    {

        public async System.Threading.Tasks.Task SendAssignedManagerEmailAsync(string manageremail, string managername, string generatorname, int id, string customer)
        {
            using var msg = new MailMessage();
            using var client = new SmtpClient("smtp-mail.outlook.com");

            msg.From = new MailAddress("ecmprojects@outlook.com");
            msg.To.Add(manageremail);

            msg.Subject = "New project!";
            msg.Body = "<p><span style='font-family:Tahoma, Geneva, sans-serif'> Hello <strong>" + managername + "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'> You have been assigned as manager on project</span><span style='color:#689f38;font-family:Tahoma, Geneva, sans-serif'><strong> " + id +  " </strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'> Project generated by: </span><span style='color:#689f38;font-family:Tahoma, Geneva, sans-serif'><strong>" +  generatorname + "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'> Customer: </span><span style='color:#689f38;font-family:Tahoma, Geneva, sans-serif'><strong>" + customer + "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'> Greetings.</span></p>";

            msg.IsBodyHtml = true;

            client.Port = 587;
            client.Credentials = new NetworkCredential("ecmprojects@outlook.com", "ecm_sysprojects");
            client.EnableSsl = true;

            try
            {
                await client.SendMailAsync(msg);
            }
            catch
            {
                return;
            }
        }

        public async System.Threading.Tasks.Task SendNewTaskEmailAsync(string email, string generatoremail, int id, string responsiblename, string generatorname, string targetdate, string customer)
        {
            using var client = new SmtpClient("electricord-com01i.mail.protection.outlook.com", 25);
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = true; // Usa las credenciales de Windows (relay interno)
            client.EnableSsl = false; // No SSL, relay interno

            using var msg = new MailMessage();
            msg.From = new MailAddress("emailrelay@ecmfg.com");
            msg.To.Add(email);
            msg.CC.Add(generatoremail);

            msg.Subject = "New pending task!";
            msg.Body = "<p><span style='font-family:Tahoma, Geneva, sans-serif'>Hello<strong> " + responsiblename +  "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'> You have a pending task to complete from the project </span><span style= 'color:#558b2f;font-family:Tahoma, Geneva, sans-serif'><strong>" + id + "</strong></span><span style= 'font-family:Tahoma, Geneva, sans-serif'> generated by <span style= 'color:#558b2f;font-family:Tahoma, Geneva, sans-serif'><strong>" +  generatorname + "</strong></span></p>" +
                        "<p><span style= 'font-family:Tahoma, Geneva, sans-serif'> Target date: </span><span style= 'color:#558b2f;font-family:Tahoma, Geneva, sans-serif'><strong> " + targetdate + " </strong></span></p>" +
                        "<p><span style='font-family:Tahoma, Geneva, sans-serif'> Customer: </span><span style='color:#689f38;font-family:Tahoma, Geneva, sans-serif'><strong>" + customer + "</strong></span></p>" +
                        "<p><span style= 'font-family:Tahoma, Geneva, sans-serif'> Greetings. </span></p>";

            msg.IsBodyHtml = true;

            try
            {
                await client.SendMailAsync(msg);
            }
            catch
            {
                return;
            }
        }

        public async System.Threading.Tasks.Task SendNewNprCreatedEmailAsync(string toEmail, string ccEmail, int projectId, string customer)
        {
            using var client = new SmtpClient("electricord-com01i.mail.protection.outlook.com", 25);
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = true; // Relay interno
            client.EnableSsl = false; // No SSL

            using var msg = new MailMessage();
            msg.From = new MailAddress("emailrelay@ecmfg.com");
            msg.To.Add(toEmail);
            if (!string.IsNullOrWhiteSpace(ccEmail)) msg.CC.Add(ccEmail);

            msg.Subject = "NEW NPR CREATED";
            msg.Body = "<p><span s tyle='font-family:Tahoma, Geneva, sans-serif'>A new NPR has been created.</span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'>Project ID: </span><span style='color:#558b2f;font-family:Tahoma, Geneva, sans-serif'><strong>" + projectId + "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'>Customer: </span><span style='color:#689f38;font-family:Tahoma, Geneva, sans-serif'><strong>" + customer + "</strong></span></p>" +
                       "<p><span style='font-family:Tahoma, Geneva, sans-serif'>Please review the tasks and dates.</span></p>";
            msg.IsBodyHtml = true;

            try
            {
                await client.SendMailAsync(msg);
            }
            catch
            {
                return;
            }
        }
    }
}